# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - develop
  path_instructions:
    - path: "src/main/java/**/*.java"
      instructions: |
        Review for:
        - Multi-tenancy security (ensure tenant isolation)
        - Proper exception handling
        - Thread-safety concerns
        - SQL injection prevention
        - Code follows existing patterns in this codebase
    - path: "src/test/**/*.java"
      instructions: |
        Review for:
        - Test coverage completeness
        - Meaningful assertions
        - Proper mocking practices
    - path: "*.sql"
      instructions: |
        Review for:
        - SQL injection vulnerabilities
        - Index usage for performance
        - Proper constraint definitions
chat:
  auto_reply: true
