ALTER TABLE users
ADD COLUMN active BOOLEAN;

UPDATE users
SET active = TRUE
WHERE active IS NULL;

ALTER TABLE users
ALTER COLUMN active SET NOT NULL;

ALTER TABLE users
ALTER COLUMN active SET DEFAULT TRUE;

